w3c/wai-video-standards-and-benefits

- index.fr.md
This would need a proofreading, I'll ask @Sylvie42 directly once the Pull request is merged.
> [FR] translation for index, complete

- index.md
@slhenry’s recent changes in the translation-prepared version to publish.
> Cherry pick changes

- index.md
> + changelog

- index.nl.md
(still need to figure out that last link)
> show-language.nl.png & spacing fixes

- index.fr.md
* deleted en anglais, which will be automatically added if the linked page is not in french
* updated internal link format to make that work
* changed player UI words (Captions, Show Transcript, Language) to match translated player
* linked to fr image
* (others I forgot to jot down)
/me will ask @notabene & Sylvie to review
> [fr] misc (list in comments)

- index.md
Note: I'm considering this a minor update for translations.
* Did not change date since content didn't change and don't want all translations to show out of date.
* Added to batch of low priority updates for translations.
> + ack in footer

- index.fr.md
> [fr] a few typos

- content-images/wai-video-standards-and-benefits/W3C_INTRO_SFHI.cs.vtt
Added Czech translation for VTT file for the intro video.
> [Ready for Review] Czech - Video Intro

- content/index.de.md
> fixing VTT for DE

- content/index.cs.md
Reverts w3c/wai-video-standards-and-benefits#87
> Revert "fixing VTT for CS"

- content/index.de.md
Reverts w3c/wai-video-standards-and-benefits#88
> Revert "fixing VTT for DE"

- content/changelog.md
- content/index.el.md
> VTT updates for EL

- content/changelog.md
- content/index.es.md
> VTT changes for ES

- content/changelog.md
- content/index.id.md
> VTT for ID

- content/changelog.md
- content/index.fr.md
> VTT changes for FR

- content/changelog.md
- content/index.ja.md
> VTT for JA

- content/changelog.md
- content/index.ko.md
> VTT for KO

- content/changelog.md
- content/index.nl.md
> VTT for NL

- content/changelog.md
- content/index.zh-hans.md
> VTT for  ZH-hans

- content/index.de.md
Direct link to preview: https://deploy-preview-126--wai-video-standards-and-benefits.netlify.app/videos/standards-and-benefits/de
Resolves https://github.com/w3c/wai-translations/issues/108
See discussion in https://github.com/w3c/wai-translations/issues/108
> Update German Translation

- content/index.ja.md
Resolves https://github.com/w3c/wai-translations/issues/168
> [Japanese] Update Video Introduction to Web Accessibility

- content/index.pl.md
I added index.pl.md file
Related pl translation for video: https://github.com/w3c/wai-website-data/pull/137
Related pl translation for ableplayer: https://github.com/ableplayer/ableplayer/pull/595 
Resolves https://github.com/w3c/wai-translations/issues/200
> [Ready for review] Polish translation
